twig:
    globals:
        enable_chat:   "%pumukit_cmar_live_chat.enable%"

parameters:
    pumukit_cmar_live_chat.enable: false
    # refresh interval in milliseconds
    pumukit_cmar_live_chat.update_interval: 5000
